import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/layout";
import { Footer } from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`antialiased`}>
        <Header />
        <main className="max-w-7xl m-auto">{children}</main>fh
        <Footer />
      </body>
    </html>
  );
}
